### ISSUE TITLE
Uncaught NotFoundError: Failed to execute 'appendChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?

### ISSUE THREAD

**Issue by misahot** [v3ss0n/goto#18]
Uncaught NotFoundError: Failed to execute 'appendChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?

**Atom Version**: 0.158.0
**System**: Mac OS X 10.10.1
**Thrown From**: [goto](https://github.com/mkleehammer/goto) package, v1.7.0
### Steps To Reproduce
1. ...
2. ...
### Stack Trace

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:5823

Error: Failed to execute 'appendChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
  at Error (native)
  at Function.jQuery.extend.buildFragment (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:5830:27)
  at PaneContainerView.jQuery.fn.extend.domManip (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:5636:22)
  at PaneContainerView.jQuery.fn.extend.before (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:5476:15)
  at PaneContainerView.jQuery.fn.(anonymous function) [as before] (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/lib/space-pen.js:396:31)
  at WorkspaceView.module.exports.WorkspaceView.appendToTop (/Applications/Atom.app/Contents/Resources/app/src/workspace-view.js:135:25)
  at GotoView.module.exports.GotoView.attach (/Users/misahot/.atom/packages/goto/lib/goto-view.coffee:37:24)
  at GotoView.module.exports.GotoView.populate (/Users/misahot/.atom/packages/goto/lib/goto-view.coffee:43:6)
  at Object.module.exports.gotoProjectSymbol (/Users/misahot/.atom/packages/goto/lib/index.coffee:39:15)
  at atom-workspace.<anonymous> (/Users/misahot/.atom/packages/goto/lib/index.coffee:18:59)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)

```

/cc @atom/core

**Comment by kayakr** [comment]
+1 on atom.io 0.174.0, "/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:5830"

**Comment by ltamrazov** [comment]
+1

**Comment by djpowers** [comment]
Just encountered this error. Unsure how to duplicate.

**Atom Version**: 0.188.0
**System**: Mac OS X 10.9.5
**Thrown From**: [goto](https://github.com/mkleehammer/goto) package, v1.7.0

### Stack Trace

Uncaught NotFoundError: Failed to execute 'appendChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:5830

Error: Failed to execute 'appendChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
  at Error (native)
  at Function.jQuery.extend.buildFragment (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:5830:27)
  at PaneContainerView.jQuery.fn.extend.domManip (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:5636:22)
  at PaneContainerView.jQuery.fn.extend.before (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:5476:15)
  at PaneContainerView.jQuery.fn.(anonymous function) [as before] (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/lib/space-pen.js:396:31)
  at WorkspaceView.module.exports.WorkspaceView.appendToTop (/Applications/Atom.app/Contents/Resources/app/src/workspace-view.js:142:25)
  at GotoView.module.exports.GotoView.attach (/Users/dpowers/.atom/packages/goto/lib/goto-view.coffee:37:24)
  at GotoView.module.exports.GotoView.populate (/Users/dpowers/.atom/packages/goto/lib/goto-view.coffee:43:6)
  at Object.module.exports.gotoFileSymbol (/Users/dpowers/.atom/packages/goto/lib/index.coffee:47:17)
  at atom-workspace.<anonymous> (/Users/dpowers/.atom/packages/goto/lib/index.coffee:19:56)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:242:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:180:20)

```

**Comment by mkleehammer** [comment]
I'm not actually using Atom anymore (I went back to emacs) so I really don't have time to maintain this.  I'd be happy to merge in pull requests and publish, but I'm really looking for someone to take the project over.  Any takers?
