### ISSUE TITLE
Broken symbolic link within Project directory breaks Cmd-Shift-R

### ISSUE THREAD

**Issue by ariofrio** [v3ss0n/goto#23]
I tried running Cmd-Shift-R on a directory which contains a broken symbolic link, and I got the following error (which prevented the Goto panel from appearing):

```
Error: ENOENT, no such file or directory '/home/ariofrio/myproject/brokenlink'
  at Error (native)
  at fs.statSync (fs.js:807:18)
  at Object.fs.statSync (/opt/atom/resources/atom/common/lib/asar.js:155:14)
  at SymbolIndex.module.exports.SymbolIndex.processDirectory (/home/ariofrio/.atom/packages/goto/lib/symbol-index.coffee:161:18)
  at SymbolIndex.module.exports.SymbolIndex.rebuild (/home/ariofrio/.atom/packages/goto/lib/symbol-index.coffee:116:8)
  at SymbolIndex.module.exports.SymbolIndex.update (/home/ariofrio/.atom/packages/goto/lib/symbol-index.coffee:108:8)
  at SymbolIndex.module.exports.SymbolIndex.getAllSymbols (/home/ariofrio/.atom/packages/goto/lib/symbol-index.coffee:99:6)
  at Object.module.exports.gotoProjectSymbol (/home/ariofrio/.atom/packages/goto/lib/index.coffee:38:22)
  at atom-workspace.<anonymous> (/home/ariofrio/.atom/packages/goto/lib/index.coffee:18:59)
  at atom-workspace.handler (/opt/atom/resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/opt/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/opt/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:243:29)
  at /opt/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/atom/resources/app/src/window-event-handler.js:172:20)
```

**Comment by acusti** [comment]
Fixed in 1.8.0
