### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '/Volumes/root/usr/sentral/bin/dialog'

### ISSUE THREAD

**Issue by Rambomst** [v3ss0n/goto#57]
I am not sure why it is trying to go to that directory when there is no dialog directory in the bin folder, in fact there are no subdirectories in the bin folder at all.

Causes: Whenever I press alt + command + down

Error: Uncaught Error: ENOENT: no such file or directory, stat '/Volumes/root/usr/sentral/bin/dialog'

Atom Version: 0.209.0

Stack Trace:

`Error: ENOENT: no such file or directory, stat '/Volumes/root/usr/sentral/bin/dialog'
  at Error (native)
  at fs.statSync (fs.js:846:18)
  at Object.fs.statSync (ATOM_SHELL_ASAR.js:206:16)
  at SymbolIndex.module.exports.SymbolIndex.processDirectory (/Users/patrick/.atom/packages/goto/lib/symbol-index.coffee:168:18)
  at SymbolIndex.module.exports.SymbolIndex.processDirectory (/Users/patrick/.atom/packages/goto/lib/symbol-index.coffee:178:8)
  at SymbolIndex.module.exports.SymbolIndex.rebuild (/Users/patrick/.atom/packages/goto/lib/symbol-index.coffee:117:8)
  at SymbolIndex.module.exports.SymbolIndex.update (/Users/patrick/.atom/packages/goto/lib/symbol-index.coffee:109:8)
  at SymbolIndex.module.exports.SymbolIndex.gotoDeclaration (/Users/patrick/.atom/packages/goto/lib/symbol-index.coffee:129:6)
  at Object.module.exports.gotoDeclaration (/Users/patrick/.atom/packages/goto/lib/index.coffee:36:22)
  at atom-workspace.atom.commands.add.goto:declaration (/Users/patrick/.atom/packages/goto/lib/index.coffee:22:31)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)`

**Comment by acusti** [comment]
Should be fixed in 1.8.0
