### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/luismartins/Sites/vagrant-wip/www...

### ISSUE THREAD

**Issue by lmartins** [v3ss0n/goto#58]
1. Delete a file that contains symbols
2. Rebuild Index
3. Try to run the goto:project-symbol command

**Atom Version**: 0.211.0
**System**: Mac OS X 10.10.4
**Thrown From**: [goto](https://github.com/v3ss0n/goto) package, v1.7.1
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/luismartins/Sites/vagrant-wip/www/rulergy/htdocs/wp-content/themes/rulergy-marketing/src/sass/render/_page-products.scss'

```
At fs.js:519

Error: ENOENT: no such file or directory, open '/Users/luismartins/Sites/vagrant-wip/www/rulergy/htdocs/wp-content/themes/rulergy-marketing/src/sass/render/_page-products.scss'
  at Error (native)
  at Object.fs.openSync (fs.js:544:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
  at Object.fs.readFileSync (fs.js:396:15)
  at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:369:29)
  at SymbolIndex.module.exports.SymbolIndex.processFile (/Users/luismartins/.atom/packages/goto/lib/symbol-index.coffee:182:15)
  at SymbolIndex.module.exports.SymbolIndex.update (/Users/luismartins/.atom/packages/goto/lib/symbol-index.coffee:113:12)
  at SymbolIndex.module.exports.SymbolIndex.getAllSymbols (/Users/luismartins/.atom/packages/goto/lib/symbol-index.coffee:100:6)
  at Object.module.exports.gotoProjectSymbol (/Users/luismartins/.atom/packages/goto/lib/index.coffee:41:22)
  at atom-workspace.atom.commands.add.goto:project-symbol (/Users/luismartins/.atom/packages/goto/lib/index.coffee:20:34)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:180:20)

```
### Commands

```
     -0:35.2.0 editor:select-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
  3x -0:30.6.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:24.7.0 pane:reopen-closed-item (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  3x -0:24.6.0 blur (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:23.2.0 core:close (div.settings-view.pane-item)
     -0:23.2.0 blur (div.settings-view.pane-item)
     -0:22.4.0 goto:project-symbol (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  3x -0:18 blur (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:17.2.0 command-palette:toggle (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:16.9.0 blur (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:13 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:12.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:12.6.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:12.6.0 goto:rebuild-index (atom-text-editor.editor.vim-mode.command-mode)
     -0:02.2.0 goto:project-symbol (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:00.4.0 blur (atom-text-editor.editor.vim-mode.command-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "symbols-view",
      "linter-jscs",
      "autocomplete",
      "autohide-tree-view",
      "powerline",
      "language-objective-c",
      "archive-view",
      "language-clojure",
      "language-c",
      "language-csharp",
      "language-gfm",
      "language-go",
      "language-java",
      "language-perl",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "welcome",
      "git-difftool",
      "layout-manager",
      "takana-atom",
      "atom-ctags"
    ],
    "projectHome": "/Users/luismartins/Sites",
    "ignoredNames": [
      ".DS_Store",
      "bower_components",
      "node_modules",
      "build",
      "jspm_packages"
    ],
    "themes": [
      "one-dark-ui",
      "atom-material-syntax"
    ]
  },
  "goto": {
    "moreIgnoredNames": "build, jspm_packages, node_modules, bower_components"
  }
}
```
### Installed Packages

``` coffee
# User
atom-alignment, v0.12.1
atom-beautify, v0.28.2
atom-material-syntax, v0.1.1
color-picker, v2.0.7
css-snippets, v0.8.0
cursor-history, v0.4.13
dash, v1.2.1
docblockr, v0.7.2
emmet, v2.3.10
feedback, v0.38.0
file-type-icons, v0.7.0
goto, v1.7.1
javascript-snippets, v1.0.0
jumpy, v2.0.9
linter, v1.0.2
linter-jshint, v0.1.6
linter-php, v0.0.15
minimap, v4.10.0
minimap-bookmarks, v0.1.0
php-debug, v0.1.2
php-twig, v4.0.0
toggle, v0.2.2
trailing-semicolon, v1.0.0
vim-mode, v0.53.0
vim-surround, v0.7.2
wordpress-api, v1.2.1

# Dev
No dev packages
```

**Comment by acusti** [comment]
Should be fixed in 1.8.0
