### ISSUE TITLE
Error with global search + unresolved symlinks

### ISSUE THREAD

**Issue by damassi** [v3ss0n/goto#59]
When attempting to do a global search `goto` errors out if it encounters a symlink that does not resolve to a place on the HD.  In my case, the symlink that it is hitting is generated by Vagrant during our provisioning process, with the vagrant instance being opaque.  Thinking:  Would it be best to just consume this error and continue on?  As it is it crashes the search.  

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [goto](https://github.com/v3ss0n/goto) package, v1.7.1

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/Users/damassi/Sites/Kindling/kindlingdev/development/kindlingapp/environment.ini'

```
At fs.js:846

Error: ENOENT: no such file or directory, stat '/Users/damassi/Sites/Kindling/kindlingdev/development/kindlingapp/environment.ini'
  at Error (native)
  at fs.statSync (fs.js:846:18)
  at Object.fs.statSync (ATOM_SHELL_ASAR.js:206:16)
  at SymbolIndex.module.exports.SymbolIndex.processDirectory (/Users/damassi/.atom/packages/goto/lib/symbol-index.coffee:168:18)
  at SymbolIndex.module.exports.SymbolIndex.rebuild (/Users/damassi/.atom/packages/goto/lib/symbol-index.coffee:117:8)
  at SymbolIndex.module.exports.SymbolIndex.update (/Users/damassi/.atom/packages/goto/lib/symbol-index.coffee:109:8)
  at SymbolIndex.module.exports.SymbolIndex.getAllSymbols (/Users/damassi/.atom/packages/goto/lib/symbol-index.coffee:100:6)
  at Object.module.exports.gotoProjectSymbol (/Users/damassi/.atom/packages/goto/lib/index.coffee:41:22)
  at atom-workspace.atom.commands.add.goto:project-symbol (/Users/damassi/.atom/packages/goto/lib/index.coffee:20:34)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:180:20)

```

### Commands

```
  2x -1:27.1.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  2x -1:26.5.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -1:25.8.0 goto:project-symbol (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -1:08.1.0 vim-mode:repeat-find-reverse (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -1:08.1.0 vim-mode:reset-command-mode (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -1:07.2.0 settings-view:open (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -1:03.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -0:56.6.0 core:backspace (atom-text-editor#goto.moreIgnoredNames.editor.mini.is-focused)
     -0:53.8.0 core:confirm (atom-text-editor#goto.moreIgnoredNames.editor.mini.is-focused)
     -0:48.1.0 core:close (div.settings-view.pane-item)
     -0:45.7.0 goto:project-symbol (ul.list-inline.tab-bar.inset-panel)
     -0:38.1.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -0:36.4.0 settings-view:open (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  2x -0:18.2.0 core:confirm (atom-text-editor#goto.moreIgnoredNames.editor.mini.is-focused)
     -0:00.8.0 goto:project-symbol (atom-text-editor.editor.vim-mode.command-mode.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "black-and-white-ui",
      "base16-eighties-dark-syntax"
    ],
    "followSymlinks": false,
    "ignoredNames": [
      "*.ini"
    ]
  },
  "goto": {
    "moreIgnoredNames": "*.ini"
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
atom-pair, v1.1.6
base16-eighties-dark-syntax, v0.1.0
black-and-white-ui, v0.1.15
close-other-tabs, v0.1.0
color-picker, v2.0.7
cursor-history, v0.4.13
goto, v1.7.1
highlight-selected, v0.10.1
indent-guide-improved, v1.4.0
language-javascript-jsx, v0.3.6
linter, v1.1.0
linter-eslint, v1.0.11
linter-php, v0.0.15
react-snippets, v0.1.4
vim-mode, v0.54.0
vim-mode-visual-block, v0.2.7

# Dev
No dev packages
```

**Comment by damassi** [comment]
closing due to https://github.com/v3ss0n/goto/issues/23
