### ISSUE TITLE
Uncaught TypeError: Cannot set property '/Users/yetone/workspace/repo/airpal/src/main/resources/a...

### ISSUE THREAD

**Issue by yetone** [v3ss0n/goto#63]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.5
**System**: Mac OS X 10.10.4
**Thrown From**: [goto](https://github.com/v3ss0n/goto) package, v1.7.1
### Stack Trace

Uncaught TypeError: Cannot set property '/Users/yetone/workspace/repo/airpal/src/main/resources/assets/javascripts/actions/QueryActions.js' of null

```
At /Users/yetone/.atom/packages/goto/lib/symbol-index.coffee:82

TypeError: Cannot set property '/Users/yetone/workspace/repo/airpal/src/main/resources/assets/javascripts/actions/QueryActions.js' of null
  at /Users/yetone/.atom/packages/goto/lib/symbol-index.coffee:82:9
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1243:25

```
### Commands

```
  3x -4:32.4.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
 18x -4:31.4.0 vim-mode:move-right (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  2x -4:28 vim-mode:move-left (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -4:26.3.0 goto:declaration (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -4:25 vim-mode-visual-block:escape (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -4:25 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -4:24.7.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -4:24.3.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  6x -4:23.8.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  2x -4:22.1.0 vim-mode:move-left (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -4:20.6.0 goto:declaration (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -4:19.1.0 vim-mode-visual-block:escape (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -4:19.1.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
  9x -4:11.9.0 blur (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -3:35.3.0 goto:declaration (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
 22x -3:17.2.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "language-babel",
      "language-javascript-jsx",
      "linter-python-pep8",
      "linter-jsxhint",
      "linter-jscs",
      "vim-mode",
      "jshint",
      "symbols-view"
    ],
    "themes": [
      "atom-material-ui",
      "material-syntax"
    ],
    "ignoredNames": [
      ".pyc"
    ]
  },
  "goto": {}
}
```
### Installed Packages

``` coffee
# User
Stylus, v1.0.0
atom-material-ui, v0.5.13
autocomplete-python, v0.5.3
clipboard-plus, v0.5.1
emmet, v2.3.12
language-rust, v0.4.4
language-viml, v0.2.0
linter, v1.3.2
linter-ansible-lint, v0.0.7
linter-csslint, v1.0.5
linter-eslint, v3.0.2
linter-pep8, v1.0.1
linter-pylint, v0.2.2
linter-scss-lint, v2.0.0
material-syntax, v0.5.0
racer, v0.16.0
react, v0.12.6
react-snippets, v0.1.4
rust-api-docs-helper, v0.5.1
vim-mode-clipboard-plus, v0.1.0
vim-mode-next, v0.57.2
vim-mode-visual-block, v0.2.13
vim-surround, v0.8.0

# Dev
No dev packages
```

**Comment by acusti** [comment]
Just published 1.8.0, which I’m hopeful resolves this issue. Please update if that isn’t the case.
