### ISSUE TITLE
Doesn't like symlinks: Uncaught Error: ENOENT: no such file or directory, stat '/Users/crucial/Sites/nsbuildout/DOING'

### ISSUE THREAD

**Issue by crucialfelix** [v3ss0n/goto#64]
1. Have a symlink in your project.
2. Command-R
3. Ouch

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.4
**Thrown From**: [goto](https://github.com/v3ss0n/goto) package, v1.7.1
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/Users/crucial/Sites/nsbuildout/DOING'

```
At fs.js:846

Error: ENOENT: no such file or directory, stat '/Users/crucial/Sites/nsbuildout/DOING'
  at Error (native)
  at fs.statSync (fs.js:846:18)
  at Object.fs.statSync (ATOM_SHELL_ASAR.js:206:16)
  at SymbolIndex.module.exports.SymbolIndex.processDirectory (/Users/crucial/.atom/packages/goto/lib/symbol-index.coffee:168:18)
  at SymbolIndex.module.exports.SymbolIndex.rebuild (/Users/crucial/.atom/packages/goto/lib/symbol-index.coffee:117:8)
  at SymbolIndex.module.exports.SymbolIndex.update (/Users/crucial/.atom/packages/goto/lib/symbol-index.coffee:109:8)
  at SymbolIndex.module.exports.SymbolIndex.gotoDeclaration (/Users/crucial/.atom/packages/goto/lib/symbol-index.coffee:129:6)
  at Object.module.exports.gotoDeclaration (/Users/crucial/.atom/packages/goto/lib/index.coffee:36:22)
  at atom-workspace.atom.commands.add.goto:declaration (/Users/crucial/.atom/packages/goto/lib/index.coffee:22:31)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
     -9:41.5.0 pane:show-previous-item (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -9:40.4.0 core:close (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -9:36.4.0 window:toggle-dev-tools (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:10.3.0 settings-view:open (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:04.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:55.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -0:55.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:21.4.0 goto:file-symbol (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:15.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:05.0 goto:declaration (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      "*.pyc",
      ".DS_Store",
      "nsclasses/nsclasses/nestseekerswww/static"
    ],
    "followSymlinks": true,
    "disabledPackages": [
      "cute-cursor",
      "language-go",
      "language-java",
      "syntax-settings",
      "term",
      "language-supercollider",
      "linter-rst",
      "rst-preview",
      "rst-preview",
      "atom-runner",
      "make-runner",
      "ide-haskell",
      "remote-edit",
      "atomatigit",
      "minimap-highlight-selected",
      "tabs-to-spaces",
      "atomic-emacs",
      "git-log",
      "autoflow",
      "autosave",
      "background-tips",
      "block-travel",
      "dash",
      "easy-motion",
      "gist-it",
      "git-blame",
      "git-difftool",
      "git-plus",
      "trailing-spaces",
      "project-colorize",
      "file-icons",
      "term2",
      "web-view",
      "atom-terminal",
      "command-logger",
      "css-color-highlighting",
      "editor-stats",
      "selection-count",
      "fancy-new-file",
      "language-clojure",
      "language-docker",
      "minimap-find-and-replace",
      "mobile-preview",
      "my-package",
      "sourcegraph-atom",
      "org",
      "paredit",
      "autocomplete",
      "jumpy",
      "atom-color-highlight",
      "angularjs-snippets",
      "todo-show",
      "autocomplete-jedi",
      "bezier-curve-editor",
      "coffee-lint",
      "python-jedi",
      "org-mode",
      "highlight-selected",
      "node-resolver",
      "next-occurrence",
      "linter-scss-lint",
      "linter-coffeelint",
      "Atom-Syntax-highlighting-for-Sass",
      "grunt-runner",
      "typewriter-sounds",
      "ide-flow",
      "atom-ctags",
      "linter-jscs",
      "atom-ternjs"
    ],
    "destroyEmptyPanes": false
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.0
atom-beautify, v0.28.11
atom-django, v0.3.0
autoclose-html, v0.18.0
autocomplete-paths, v1.0.2
autocomplete-plus-python-jedi, v0.3.6
autocomplete-python, v0.5.3
color-picker, v2.0.11
cursor-history, v0.4.18
django-templates, v0.5.0
editorconfig, v1.0.1
emmet, v2.3.12
goto, v1.7.1
javascript-snippets, v1.0.0
language-crontab, v0.1.0
language-jade, v0.6.2
language-restructuredtext, v0.7.0
language-swift, v0.4.0
last-cursor-position, v0.9.0
linter, v1.4.1
linter-csslint, v1.0.5
linter-jshint, v1.1.5
linter-jsxhint, v0.1.2
linter-pep8, v1.0.1
linter-pylint, v0.2.2
minimap, v4.12.3
pain-split, v1.4.0
pigments, v0.11.0
project-manager, v1.15.11
python-autopep8, v0.1.3
react, v0.12.6
regex-railroad-diagram, v0.8.4
rename-tabs, v0.1.1
set-syntax, v0.3.0
symbol-gen, v1.0.0
tree-view-git-status, v0.1.2
vim-mode, v0.58.0
zentabs, v0.8.6

# Dev
No dev packages
```

**Comment by acusti** [comment]
Should be fixed in 1.8.0
