### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, scandir 'atom://config'

### ISSUE THREAD

**Issue by stugol** [v3ss0n/goto#66]
[Enter steps to reproduce below:]
1. Press shift-cmd-r

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.4
**Thrown From**: [goto](https://github.com/v3ss0n/goto) package, v1.7.1
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, scandir 'atom://config'

```
At fs.js:805

Error: ENOENT: no such file or directory, scandir 'atom://config'
  at Error (native)
  at Object.fs.readdirSync (fs.js:805:18)
  at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:441:28)
  at SymbolIndex.module.exports.SymbolIndex.processDirectory (/Users/infinity/.atom/packages/goto/lib/symbol-index.coffee:163:18)
  at SymbolIndex.module.exports.SymbolIndex.rebuild (/Users/infinity/.atom/packages/goto/lib/symbol-index.coffee:117:8)
  at SymbolIndex.module.exports.SymbolIndex.update (/Users/infinity/.atom/packages/goto/lib/symbol-index.coffee:109:8)
  at SymbolIndex.module.exports.SymbolIndex.getAllSymbols (/Users/infinity/.atom/packages/goto/lib/symbol-index.coffee:100:6)
  at Object.module.exports.gotoProjectSymbol (/Users/infinity/.atom/packages/goto/lib/index.coffee:41:22)
  at atom-workspace.atom.commands.add.goto:project-symbol (/Users/infinity/.atom/packages/goto/lib/index.coffee:20:34)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
     -0:24.8.0 core:close (button.btn.icon.enablement.icon-playback-play)
  3x -0:22.1.0 tab-switcher:next (atom-text-editor.editor.is-focused)
     -0:19.4.0 nuclide-click-to-symbol:activate (atom-text-editor.editor.is-focused)
  2x -0:19.3.0 window:decrease-font-size (atom-text-editor.editor.is-focused)
     -0:18.3.0 tab-switcher:next (atom-text-editor.editor.is-focused)
     -0:17.7.0 nuclide-click-to-symbol:activate (atom-text-editor.editor.is-focused)
     -0:17.5.0 window:decrease-font-size (atom-text-editor.editor.is-focused)
  2x -0:16.8.0 tab-switcher:next (atom-text-editor.editor.is-focused)
  2x -0:14.7.0 nuclide-click-to-symbol:activate (atom-text-editor.editor.is-focused)
     -0:06.7.0 go-to-line:toggle (atom-text-editor.editor.is-focused)
     -0:05.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:04.9.0 nuclide-click-to-symbol:activate (atom-text-editor.editor.is-focused)
     -0:04.4.0 goto:project-symbol (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "language-ruby",
      "spell-check",
      "wrap-guide",
      "wrap-guide",
      "deprecation-cop",
      "trailing-spaces",
      "go-plus",
      "go-playground",
      "linter-ruby",
      "racer",
      "minimap",
      "symbols-view",
      "atom-slime",
      "build",
      "cargo-test-runner",
      "language-rust",
      "multi-wrap-guide",
      "rust-api-docs-helper",
      "toggle-gutter",
      "linter-rust"
    ]
  },
  "goto": {}
}
```
### Installed Packages

``` coffee
# User
atom-ctags, v4.1.4
atom-dlang, v1.1.2
autocomplete-ruby, v0.1.0
code-links, v0.3.11
color-picker, v2.0.11
fold-comments, v0.5.0
fold-functions, v0.3.1
goto, v1.7.1
haxe, v0.8.5
indent-guide-improved, v1.4.1
language-crystal-actual, v0.28.0
language-dylan, v0.7.3
language-haxe, v0.3.0
language-lisp, v0.1.2
language-ruby-without-erb, v0.52.0
linter, v1.3.4
linter-crystal, v3.0.0
nuclide-click-to-symbol, v0.0.22
nuclide-find-references, v0.0.30
one-tab, v0.8.0
pigments, v0.9.3
ruby-block, v0.3.5
tab-switcher, v1.2.1

# Dev
No dev packages
```

**Comment by acusti** [comment]
Should be fixed in 1.8.0
