### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '/Users/xxx/git/xxx/yyy/data'

### ISSUE THREAD

**Issue by daPhantom** [v3ss0n/goto#67]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.16
**System**: Mac OS X 10.10.5
**Thrown From**: [goto](https://github.com/v3ss0n/goto) package, v1.7.1
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/Users/xxx/git/xxx/yyy/data'

```
At ATOM_SHELL_ASAR.js:118

Error: ENOENT: no such file or directory, stat '/Users/xxx/git/xxx/yyy/data'
  at Error (native)
  at fs.statSync (fs.js:854:18)
  at Object.fs.statSync (ATOM_SHELL_ASAR.js:225:16)
  at SymbolIndex.module.exports.SymbolIndex.processDirectory (/Users/xxx/.atom/packages/goto/lib/symbol-index.coffee:168:18)
  at SymbolIndex.module.exports.SymbolIndex.rebuild (/Users/xxx/.atom/packages/goto/lib/symbol-index.coffee:117:8)
  at SymbolIndex.module.exports.SymbolIndex.update (/Users/xxx/.atom/packages/goto/lib/symbol-index.coffee:109:8)
  at SymbolIndex.module.exports.SymbolIndex.getAllSymbols (/Users/xxxx/.atom/packages/goto/lib/symbol-index.coffee:100:6)
  at Object.module.exports.gotoProjectSymbol (/Users/xxx/.atom/packages/goto/lib/index.coffee:41:22)
  at atom-workspace.atom.commands.add.goto:project-symbol (/Users/xxx/.atom/packages/goto/lib/index.coffee:20:34)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```
### Commands

```
     -0:26 core:select-all (atom-text-editor#core.ignoredNames.editor.mini.is-focused)
     -0:25.7.0 core:backspace (atom-text-editor#core.ignoredNames.editor.mini.is-focused)
     -0:25.4.0 core:confirm (atom-text-editor#core.ignoredNames.editor.mini.is-focused)
     -0:24.6.0 core:close (atom-text-editor#core.ignoredNames.editor.mini.is-focused)
     -0:24.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:23 settings-view:open (atom-text-editor.editor.is-focused)
  2x -0:20.2.0 core:save (atom-text-editor#core.ignoredNames.editor.mini.is-focused)
     -0:15 core:backspace (atom-text-editor#core.ignoredNames.editor.mini.is-focused)
     -0:10.9.0 editor:consolidate-selections (atom-text-editor#core.ignoredNames.editor.mini.is-focused)
     -0:10.9.0 core:cancel (atom-text-editor#core.ignoredNames.editor.mini.is-focused)
     -0:10.5.0 core:save (atom-text-editor#core.ignoredNames.editor.mini.is-focused)
     -0:07.5.0 core:close (div.settings-view.pane-item)
  2x -0:05.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:04.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:04.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:02.6.0 goto:project-symbol (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "projectHome": "/Users/xxx/git",
    "ignoredNames": [
      "/data /tmp /logs"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
color-picker, v2.0.12
file-icons, v1.6.9
goto, v1.7.1
linter, v1.6.0
linter-js-standard, v3.2.0
linter-php, v1.0.3
minimap, v4.13.3
php-getters-setters, v0.5.5
pigments, v0.15.0
symbol-gen, v1.0.0
symbols-tree-view, v0.10.0

# Dev
No dev packages
```

The data folder is a symlink. This seems to break the goto plugin. Any idea how to fix it? Adding these folders to atom ignore didn't work.

**Comment by acusti** [comment]
Should be fixed in 1.8.0
