### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat 'path/.../app.css'

### ISSUE THREAD

**Issue by Globegitter** [v3ss0n/goto#71]
[Enter steps to reproduce below:]
1. I think I am getting this error due to a symlink that links to a file that does not exist

**Atom Version**: 1.3.0-beta4
**System**: Ubuntu 14.04.3
**Thrown From**: [goto](https://github.com/v3ss0n/goto) package, v1.7.1
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/home/some/path/.../css/app.css'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, stat '/home/some/path/.../css/app.css'
    at Error (native)
    at fs.statSync (fs.js:854:18)
    at Object.fs.statSync (ATOM_SHELL_ASAR.js:225:16)
    at SymbolIndex.module.exports.SymbolIndex.processDirectory (/home/mpadourek/.atom/packages/goto/lib/symbol-index.coffee:168:18)
    at SymbolIndex.module.exports.SymbolIndex.processDirectory (/home/mpadourek/.atom/packages/goto/lib/symbol-index.coffee:178:8)
    at SymbolIndex.module.exports.SymbolIndex.processDirectory (/home/mpadourek/.atom/packages/goto/lib/symbol-index.coffee:178:8)
    at SymbolIndex.module.exports.SymbolIndex.processDirectory (/home/mpadourek/.atom/packages/goto/lib/symbol-index.coffee:178:8)
    at SymbolIndex.module.exports.SymbolIndex.processDirectory (/home/mpadourek/.atom/packages/goto/lib/symbol-index.coffee:178:8)
    at SymbolIndex.module.exports.SymbolIndex.processDirectory (/home/mpadourek/.atom/packages/goto/lib/symbol-index.coffee:178:8)
    at SymbolIndex.module.exports.SymbolIndex.processDirectory (/home/mpadourek/.atom/packages/goto/lib/symbol-index.coffee:178:8)
    at SymbolIndex.module.exports.SymbolIndex.processDirectory (/home/mpadourek/.atom/packages/goto/lib/symbol-index.coffee:178:8)
    at SymbolIndex.module.exports.SymbolIndex.rebuild (/home/mpadourek/.atom/packages/goto/lib/symbol-index.coffee:117:8)
    at atom-workspace.atom.commands.add.goto:rebuild-index (/home/mpadourek/.atom/packages/goto/lib/index.coffee:23:39)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom-beta/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom-beta/resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom-beta/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom-beta/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom-beta/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom-beta/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom-beta/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom-beta/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom-beta/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom-beta/resources/app.asar/src/window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (/usr/share/atom-beta/resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -7:05.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -7:02.5.0 symbols-view:toggle-file-symbols (atom-text-editor.editor.is-focused)
  5x -7:01.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -7:00.6.0 core:move-up (atom-text-editor.editor.mini.is-focused)
  2x -7:00.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -6:59.4.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -6:58.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -6:49.6.0 symbols-view:toggle-file-symbols (atom-text-editor.editor.is-focused)
     -6:49.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -6:49.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -6:35.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -6:16 command-palette:toggle (atom-text-editor.editor.is-focused)
     -6:11.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -6:11.1.0 goto:rebuild-index (atom-text-editor.editor)
     -0:00.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:00.3.0 core:move-up (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "disabledPackages": [
      "symbols-view"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
goto, v1.7.1
pigments, v0.19.0
pretty-json, v0.4.1

# Dev
No dev packages
```

It is a complicated to explain why there would be a symlink pointing to a file that does not exist, but the easy solution for me right now is to just ignore that folder. Just thought to report that since it would be nice to have some error handling for it :)

**Comment by acusti** [comment]
Should be fixed in 1.8.0
