### ISSUE TITLE
Uncaught TypeError: Cannot set property '/opt/lampp/htdocs/geschool/protected/models/smart/GetopT...

### ISSUE THREAD

**Issue by andhikayuana** [v3ss0n/goto#73]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Linux Mint
**Thrown From**: [goto](https://github.com/v3ss0n/goto) package, v1.7.1
### Stack Trace

Uncaught TypeError: Cannot set property '/opt/lampp/htdocs/geschool/protected/models/smart/GetopTreeModel.php' of null

```
At /home/yuana/.atom/packages/goto/lib/symbol-index.coffee:82

TypeError: Cannot set property '/opt/lampp/htdocs/geschool/protected/models/smart/GetopTreeModel.php' of null
    at /home/yuana/.atom/packages/goto/lib/symbol-index.coffee:82:9
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at /opt/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1276:25
```
### Commands

```
  2x -2:57.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:14.2.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
  3x -1:10 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:09.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -1:08.0 goto:file-symbol (atom-text-editor.editor.is-focused)
     -0:35.1.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
  3x -0:33.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  4x -0:30.4.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:29 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:24.2.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:17.9.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:14.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:14.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:14.1.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
 23x -0:09.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:01.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "monokai"
    ],
    "autoHideMenuBar": true,
    "disabledPackages": [
      "emmet",
      "goto"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-material-ui, v0.8.0
atom-yii, v0.4.1
color-picker, v2.0.14
highlight-selected, v0.11.1
minimap, v4.16.2
minimap-highlight-selected, v4.3.1
monokai, v0.18.0
open-recent, v4.0.1

# Dev
No dev packages
```

**Comment by acusti** [comment]
Just published 1.8.0, which I’m hopeful resolves this issue. Please update if that isn’t the case.
