### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, scandir 'C:\Users\spyzor-pc\AppData\Local\atom...

### ISSUE THREAD

**Issue by Gil-1** [v3ss0n/goto#75]
[Enter steps to reproduce below:]
1. opened a php file (wordpress 4.4 wp-cron.php)
2. selected get_row and tried to execute Goto Declaration

**Atom Version**: 1.3.1
**System**: Unknown Windows Version
**Thrown From**: [goto](https://github.com/v3ss0n/goto) package, v1.7.1
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, scandir 'C:\Users\spyzor-pc\AppData\Local\atom\app-1.3.1\atom:\about'

```
At fs.js:813

Error: ENOENT: no such file or directory, scandir 'C:\Users\spyzor-pc\AppData\Local\atom\app-1.3.1\atom:\about'
    at Error (native)
    at Object.fs.readdirSync (fs.js:813:18)
    at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:454:28)
    at SymbolIndex.module.exports.SymbolIndex.processDirectory (file:///C:/Users/spyzor-pc/.atom/packages/goto/lib/symbol-index.coffee:163:18)
    at SymbolIndex.module.exports.SymbolIndex.rebuild (file:///C:/Users/spyzor-pc/.atom/packages/goto/lib/symbol-index.coffee:117:8)
    at SymbolIndex.module.exports.SymbolIndex.update (file:///C:/Users/spyzor-pc/.atom/packages/goto/lib/symbol-index.coffee:109:8)
    at SymbolIndex.module.exports.SymbolIndex.gotoDeclaration (file:///C:/Users/spyzor-pc/.atom/packages/goto/lib/symbol-index.coffee:129:6)
    at Object.module.exports.gotoDeclaration (file:///C:/Users/spyzor-pc/.atom/packages/goto/lib/index.coffee:36:22)
    at atom-workspace.atom.commands.add.goto:declaration (file:///C:/Users/spyzor-pc/.atom/packages/goto/lib/index.coffee:22:31)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\spyzor-pc\AppData\Local\atom\app-1.3.1\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\spyzor-pc\AppData\Local\atom\app-1.3.1\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\spyzor-pc\AppData\Local\atom\app-1.3.1\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (C:\Users\spyzor-pc\AppData\Local\atom\app-1.3.1\resources\app.asar\src\atom-environment.js:1016:28)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.ipc.sendSync (C:\Users\spyzor-pc\AppData\Local\atom\app-1.3.1\resources\atom.asar\renderer\api\lib\ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\spyzor-pc\AppData\Local\atom\app-1.3.1\resources\atom.asar\renderer\api\lib\remote.js:143:29)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\spyzor-pc\AppData\Local\atom\app-1.3.1\resources\app.asar\src\context-menu-manager.js:156:33)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (C:\Users\spyzor-pc\AppData\Local\atom\app-1.3.1\resources\app.asar\src\window-event-handler.js:250:47)
    at HTMLDocument.<anonymous> (C:\Users\spyzor-pc\AppData\Local\atom\app-1.3.1\resources\app.asar\src\window-event-handler.js:3:61)
```
### Commands

```
     -0:12.9.0 symbols-view:go-to-declaration (atom-text-editor.editor.is-focused)
     -0:09.0 tree-view:reveal-active-file (atom-text-editor.editor.is-focused)
     -0:02.9.0 goto:declaration (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "linter-phpmd"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autoclose-html, v0.19.0
autocomplete-php, v0.3.7
color-picker, v2.0.14
file-icons, v1.6.13
goto, v1.7.1
highlight-line, v0.11.0
highlight-selected, v0.11.1
linter, v1.11.3
linter-csslint, v1.1.0
linter-js-yaml, v1.2.5
linter-jshint, v1.2.1
linter-phpcs, v1.3.0
linter-tidy, v1.0.1
minimap, v4.18.0
minimap-highlight-selected, v4.3.1
open-recent, v4.0.1
php-cs-fixer, v2.5.1
php-integrator-autocomplete-plus, v0.3.0
php-integrator-base, v0.3.1
php-integrator-navigation, v0.2.4
php-integrator-tooltips, v0.2.1

# Dev
No dev packages
```

**Comment by acusti** [comment]
Should be fixed by 1.8.0
