### ISSUE TITLE
Uncaught TypeError: _this.toggle is not a function

### ISSUE THREAD

**Issue by sdaitzman** [v3ss0n/goto#81]
Let me know if this is the wrong repo to be submitting this issue to. It has been auto-generated by Atom.

[Enter steps to reproduce below:]
1. Hit Shift-CMD-P
2. Select "toggle markdown preview" but actually select "toggle mobile preview" by accident

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [goto](https://github.com/v3ss0n/goto) package, v1.7.1
### Stack Trace

Uncaught TypeError: _this.toggle is not a function

```
At /Users/samuel/.atom/packages/goto/lib/index.coffee:19

TypeError: _this.toggle is not a function
    at atom-workspace.atom.commands.add.mobile-preview:toggle (/Users/samuel/.atom/packages/goto/lib/index.coffee:19:36)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:16.5.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:13.7.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:13.7.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:13 core:backspace (atom-text-editor.editor.is-focused)
     -0:12.5.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:11.5.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:11.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:10.6.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:10.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:10.2.0 emmet:toggle-comment (atom-text-editor.editor.is-focused)
     -0:10.2.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -0:07.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:06.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:04.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:03.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.2.0 mobile-preview:toggle (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "atom-processing",
      "wrap-guide",
      "symbols-view",
      "metrics",
      "vim-mode",
      "jslint"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
.bin, vundefined
atom-beautify, v0.28.19
atom-handlebars, v1.3.0
atom-ternjs, v0.12.1
auto-indent, v0.5.0
autocomplete-python, v1.2.4
build-gulp, v0.6.0
build-make, v0.7.0
color-picker, v2.0.14
editorconfig, v1.2.2
emmet, v2.3.17
file-icons, v1.6.13
goto, v1.7.1
highlight-line, v0.11.0
hyperclick, vundefined
jquery-snippets, v11.0.0
language-arduino, v0.4.1
language-docker, v1.1.6
language-fish-shell, v1.0.2
language-julia, v0.4.1
linter, v1.11.3
linter-alex, v1.6.0
minimap, v4.18.2
minimap-bookmarks, v0.2.0
minimap-codeglance, v0.4.5
minimap-color-highlight, v4.1.4
minimap-find-and-replace, v4.4.0
minimap-git-diff, v4.1.8
minimap-pigments, v0.1.7
minimap-selection, v4.3.1
nuclide-health, v0.0.35
pigments, v0.19.3
processing-language, v0.2.0
python-tools, v0.6.7
react, v0.12.10
tag, v0.3.0
tree-view-finder, v0.2.1

# Dev
No dev packages
```

**Comment by acusti** [comment]
That’s surprising. Thanks for reporting it! Fixed in 1.8.2
