### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '/Users/username/Projects/ProjectNAme/doc/api'

### ISSUE THREAD

**Issue by Riveascore** [v3ss0n/goto#82]
### Steps to Reproduce

The "file" it broke on was a **symbolic link** that was committed to Github. It happened when trying to build the index for global symbol goto.

---

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.1
**Thrown From**: [goto](https://github.com/v3ss0n/goto) package, v1.7.1
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/Users/username/Projects/ProjectName/doc/api'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, stat '/Users/username/Projects/ProjectName/doc/api'
    at Error (native)
    at fs.statSync (fs.js:854:18)
    at Object.fs.statSync (ATOM_SHELL_ASAR.js:225:16)
    at SymbolIndex.module.exports.SymbolIndex.processDirectory (/Users/username/.atom/packages/goto/lib/symbol-index.coffee:168:18)
    at SymbolIndex.module.exports.SymbolIndex.processDirectory (/Users/username/.atom/packages/goto/lib/symbol-index.coffee:178:8)
    at SymbolIndex.module.exports.SymbolIndex.rebuild (/Users/username/.atom/packages/goto/lib/symbol-index.coffee:117:8)
    at SymbolIndex.module.exports.SymbolIndex.update (/Users/username/.atom/packages/goto/lib/symbol-index.coffee:109:8)
    at SymbolIndex.module.exports.SymbolIndex.getAllSymbols (/Users/username/.atom/packages/goto/lib/symbol-index.coffee:100:6)
    at Object.module.exports.gotoProjectSymbol (/Users/username/.atom/packages/goto/lib/index.coffee:41:22)
    at atom-workspace.atom.commands.add.goto:project-symbol (/Users/username/.atom/packages/goto/lib/index.coffee:20:34)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/username/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Users/username/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Users/username/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Users/username/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1010:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```
### Commands

```
     -8:29.6.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -8:27.9.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -8:27.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -7:54.7.0 core:close (atom-text-editor.editor.is-focused)
     -7:54.1.0 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -7:53.5.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -7:49.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -7:38.5.0 core:copy (atom-text-editor.editor.is-focused)
     -7:37.6.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -7:37.4.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -7:29.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -7:29.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -7:28.5.0 core:copy (atom-text-editor.editor.is-focused)
     -5:17.5.0 goto:rebuild-index (atom-text-editor.editor.is-focused)
     -2:32.8.0 emmet:reflect-css-value (atom-text-editor.editor.is-focused)
     -2:26.1.0 goto:project-symbol (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "packagesWithKeymapsDisabled": [
      "erb-helper"
    ],
    "disabledPackages": [
      "atom-terminal-panel"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
close-on-left, v0.3.0
copy-filename, v1.0.1
emmet, v2.3.17
goto, v1.7.1
linter, v1.11.3
linter-ruby, v1.2.0
set-syntax, v0.3.0

# Dev
No dev packages
```

**Comment by acusti** [comment]
Should be fixed by 1.8.0
