### ISSUE TITLE
Uncaught TypeError: Cannot set property 'C:\Users\spotted\.atom\config.cson' of null

### ISSUE THREAD

**Issue by Deviad** [v3ss0n/goto#85]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.6.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [goto](https://github.com/v3ss0n/goto) package, v1.7.1
### Stack Trace

Uncaught TypeError: Cannot set property 'C:\Users<user>.atom\config.cson' of null

```
At /C:/users/<user>/.atom/packages/goto/lib/symbol-index.coffee:98

TypeError: Cannot set property 'C:\users\<user>\.atom\config.cson' of null
    at file:///C:/Users/<user>/.atom/packages/goto/lib/symbol-index.coffee:82:9
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\<user>\AppData\Local\atom\app-1.6.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\<user>\AppData\Local\atom\app-1.6.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at C:\Users\<user>\AppData\Local\atom\app-1.6.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1327:25
```
### Commands

```
     -3:25 core:cut (atom-text-editor.editor.is-focused)
     -3:23.2.0 core:paste (atom-text-editor.editor.is-focused)
     -3:21.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:20.7.0 core:move-down (atom-text-editor.editor.is-focused)
     -3:20.5.0 core:move-left (atom-text-editor.editor.is-focused)
  4x -3:20 core:backspace (atom-text-editor.editor.is-focused)
     -3:08.9.0 core:save (atom-text-editor.editor.is-focused)
     -3:06.7.0 linter:lint (atom-text-editor.editor.is-focused)
     -3:03.3.0 goto:declaration (atom-text-editor.editor.is-focused)
     -2:54.7.0 goto:file-symbol (atom-text-editor.editor.is-focused)
     -2:53.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -2:53.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -2:51.2.0 emmet:reflect-css-value (atom-text-editor.editor.is-focused)
     -2:22.7.0 linter:lint (atom-text-editor.editor)
  7x -2:18.8.0 emmet:reflect-css-value (atom-text-editor.editor.is-focused)
 19x -2:09.8.0 goto:declaration (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "symbols-view"
    ],
    "packagesWithKeymapsDisabled": [
      "goto"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
aligner-php, v1.0.0
angularjs, v0.3.4
atom-beautify, v0.28.26
atom-typescript, v8.4.0
autocomplete-php, v0.3.7
color-picker, v2.1.1
emmet, v2.4.2
file-icons, v1.6.18
highlight-line, v0.11.1
highlight-selected, v0.11.2
linter, v1.11.4
linter-csslint, v1.3.2
linter-htmlhint, v1.1.0
linter-js-yaml, v1.2.5
linter-jshint, v2.0.3
linter-php, v1.2.0
linter-phpcs, v1.3.1
linter-phpmd, v1.4.1
linter-scss-lint, v2.5.1
linter-tidy, v2.1.0
minimap, v4.21.0
pigments, v0.24.5
project-manager, v2.7.6
wordpress-api, v1.2.2

# Dev
No dev packages
```

**Comment by acusti** [comment]
Just published 1.8.0, which I’m hopeful resolves this issue. Please update if that isn’t the case.
