### ISSUE TITLE
Uncaught TypeError: Cannot set property '/Users/tajhul/Sites/campaign-api/app/Http/Controllers/Te...

### ISSUE THREAD

**Issue by tajhulfaijin** [v3ss0n/goto#87]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.6.2
**System**: Mac OS X 10.11.3
**Thrown From**: [goto](https://github.com/v3ss0n/goto) package, v1.7.1
### Stack Trace

Uncaught TypeError: Cannot set property '/Users/tajhul/Sites/campaign-api/app/Http/Controllers/TestController.php' of null

```
At /Users/tajhul/.atom/packages/goto/lib/symbol-index.coffee:82

TypeError: Cannot set property '/Users/tajhul/Sites/campaign-api/app/Http/Controllers/TestController.php' of null
    at /Users/tajhul/.atom/packages/goto/lib/symbol-index.coffee:82:9
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1327:25
```
### Commands

```
     -7:43.8.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -7:43.8.0 core:cancel (atom-text-editor.editor.is-focused)
     -5:25.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:49.7.0 window:decrease-font-size (atom-text-editor.editor.is-focused)
     -3:46.4.0 goto:file-symbol (atom-text-editor.editor.is-focused)
     -3:45.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -3:45.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -2:05.6.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
  3x -1:22.4.0 symbols-view:go-to-declaration (atom-text-editor.editor.is-focused)
     -0:25.4.0 core:close (button.btn.icon.enablement.icon-playback-play)
     -0:02.5.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:02.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:02.5.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:02.3.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:02.3.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:02.3.0 editor:indent (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "goto",
      "php-integrator-navigation"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.29.1
php-cs-fixer, v2.5.6

# Dev
No dev packages
```

**Comment by acusti** [comment]
Just published 1.8.0, which I’m hopeful resolves this issue. Please update if that isn’t the case.
