### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '/Users/che/workspace/funny/geonosis/node...

### ISSUE THREAD

**Issue by cynosures** [v3ss0n/goto#88]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.1
**System**: Mac OS X 10.10.5
**Thrown From**: [goto](https://github.com/v3ss0n/goto) package, v1.7.1
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/Users/che/workspace/funny/geonosis/node_modules/.bin/atob'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, stat '/Users/che/workspace/funny/geonosis/node_modules/.bin/atob'
    at Error (native)
    at fs.statSync (fs.js:897:18)
    at Object.fs.statSync (ATOM_SHELL_ASAR.js:264:16)
    at SymbolIndex.module.exports.SymbolIndex.processDirectory (/Users/che/.atom/packages/goto/lib/symbol-index.coffee:168:18)
    at SymbolIndex.module.exports.SymbolIndex.processDirectory (/Users/che/.atom/packages/goto/lib/symbol-index.coffee:178:8)
    at SymbolIndex.module.exports.SymbolIndex.processDirectory (/Users/che/.atom/packages/goto/lib/symbol-index.coffee:178:8)
    at SymbolIndex.module.exports.SymbolIndex.rebuild (/Users/che/.atom/packages/goto/lib/symbol-index.coffee:117:8)
    at SymbolIndex.module.exports.SymbolIndex.update (/Users/che/.atom/packages/goto/lib/symbol-index.coffee:109:8)
    at SymbolIndex.module.exports.SymbolIndex.gotoDeclaration (/Users/che/.atom/packages/goto/lib/symbol-index.coffee:129:6)
    at Object.module.exports.gotoDeclaration (/Users/che/.atom/packages/goto/lib/index.coffee:36:22)
    at atom-workspace.atom.commands.add.goto:declaration (/Users/che/.atom/packages/goto/lib/index.coffee:22:31)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1106:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:327:25)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
```
### Commands

```
     -0:49.4.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  4x -0:48 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:47.1.0 application:open (atom-text-editor.editor.mini.is-focused)
     -0:12 goto:declaration (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:00.4.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:00.4.0 application:open (atom-text-editor.editor.mini)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
atomic-chrome, v0.3.0
goto, v1.7.1
minimap, v4.21.0
pigments, v0.26.0
terminal-plus, v0.14.5
vim-mode, v0.65.0

# Dev
No dev packages
```

**Comment by acusti** [comment]
Just published 1.8.0, which I’m hopeful resolves this issue. Please update if that isn’t the case.
