### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '/project_folder/node_modules'

### ISSUE THREAD

**Issue by max-mykhailenko** [v3ss0n/goto#91]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [goto](https://github.com/v3ss0n/goto) package, v1.7.1
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/Users/max/Work/Projects/rgb-lab.net/node_modules'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, stat '/Users/max/Work/Projects/rgb-lab.net/node_modules'
    at Error (native)
    at fs.statSync (fs.js:897:18)
    at Object.fs.statSync (ATOM_SHELL_ASAR.js:264:16)
    at SymbolIndex.module.exports.SymbolIndex.processDirectory (/Users/max/.atom/packages/goto/lib/symbol-index.coffee:168:18)
    at SymbolIndex.module.exports.SymbolIndex.rebuild (/Users/max/.atom/packages/goto/lib/symbol-index.coffee:117:8)
    at atom-workspace.atom.commands.add.goto:rebuild-index (/Users/max/.atom/packages/goto/lib/index.coffee:23:39)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
  2x -0:28.3.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
 52x -0:27.8.0 core:move-down (atom-text-editor.editor.is-focused)
 21x -0:26.6.0 core:move-up (atom-text-editor.editor.is-focused)
  3x -0:25.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:24.7.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:24.4.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:24.2.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:23.9.0 core:move-left (atom-text-editor.editor.is-focused)
  5x -0:23.6.0 goto:declaration (atom-text-editor.editor.is-focused)
     -0:08.6.0 tree-view:remove (span.name.icon.icon-file-text)
     -0:04.9.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:04.9.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:04.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -0:01.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:00.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.6.0 goto:rebuild-index (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "symbols-view"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "php",
      "views_cache",
      "storage"
    ],
    "themes": [
      "one-dark-ui",
      "oceanic-next"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
docblockr, v0.7.3
goto, v1.7.1
language-babel, v2.31.0
linter, v1.11.14
linter-eslint, v7.2.4
oceanic-next, v0.1.2
php-twig, v4.0.0
project-plus, v0.9.0

# Dev
No dev packages
```

**Comment by acusti** [comment]
Just published 1.8.0, which I’m hopeful resolves this issue. Please update if that isn’t the case.
