### ISSUE TITLE
Uncaught TypeError: Cannot set property '~/Documents/Projects/onApp/onapp-workflows-engine/app/co...

### ISSUE THREAD

**Issue by sveredyuk** [v3ss0n/goto#93]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.9.9
**System**: Mac OS X 10.11.6
**Thrown From**: [goto](https://github.com/v3ss0n/goto) package, v1.7.1
### Stack Trace

Uncaught TypeError: Cannot set property '/Users/volodimir/Documents/Projects/onApp/onapp-workflows-engine/app/concepts/on_app/workflows/step/cell/form.rb' of null

```
At /Users/volodimir/.atom/packages/goto/lib/symbol-index.coffee:98

TypeError: Cannot set property '/Users/volodimir/Documents/Projects/onApp/onapp-workflows-engine/app/concepts/on_app/workflows/step/cell/form.rb' of null
    at /Users/volodimir/.atom/packages/goto/lib/symbol-index.coffee:98:52
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/event-kit/lib/emitter.js:129:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1429:25
```
### Commands

```
  2x -0:58.3.0 core:close (atom-text-editor.editor.is-focused)
     -0:52.7.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:52.4.0 core:copy (atom-text-editor.editor.is-focused)
     -0:52 core:paste (atom-text-editor.editor.is-focused)
     -0:37.6.0 pane:show-item-1 (atom-text-editor.editor.is-focused)
     -0:37.4.0 pane:show-item-2 (atom-text-editor.editor.is-focused)
     -0:36.6.0 pane:show-item-1 (atom-text-editor.editor.is-focused)
     -0:36.1.0 pane:show-item-2 (atom-text-editor.editor.is-focused)
     -0:34.7.0 pane:show-item-1 (atom-text-editor.editor.is-focused)
     -0:34.5.0 pane:show-item-2 (atom-text-editor.editor.is-focused)
     -0:32.4.0 goto-definition:go (atom-text-editor.editor.is-focused)
     -0:28.3.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:24.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:08.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -0:03.7.0 core:close (button.btn.btn-default.selected)
     -0:00.3.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "linter-rubocop"
    ],
    "packagesWithKeymapsDisabled": [
      "emmet"
    ],
    "projectHome": "/Users/volodimir/Documents/Projects",
    "themes": [
      "solarized-one-light-ui",
      "solarized-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
activate-power-mode, v0.8.1 (active)
color-picker, v2.2.2 (active)
emmet, v2.4.3 (active)
file-icons, v1.7.19 (active)
git-time-machine, v1.5.3 (active)
goto, v1.7.1 (inactive)
goto-definition, v1.1.19 (active)
language-dots, v0.0.4 (active)
language-haml, v0.24.0 (active)
language-rspec, v0.5.0 (active)
linter, v1.11.16 (active)
linter-haml, v1.2.1 (active)
linter-rubocop, v0.4.7 (inactive)
linter-ruby, v1.2.2 (active)
minimap, v4.24.7 (active)
monokai-shade, v0.3.5 (inactive)
pigments, v0.34.0 (active)
rails-snippets, v2.7.0 (inactive)
ruby-block, v0.3.5 (active)
ruby-slim, v0.2.0 (active)
solarized-one-light-ui, v1.1.11 (active)
space-deep, v0.3.2 (active)
tabs-to-spaces, v1.0.2 (active)
trailing-spaces, v0.3.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (active)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (active)
go-to-line, v0.31.0 (active)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.1 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (active)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.1 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by acusti** [comment]
Just published 1.8.0, which I’m hopeful resolves this issue. Please update if that isn’t the case.
