### ISSUE TITLE
Goto Project Symbol or Reindexing causes an error

### ISSUE THREAD

**Issue by dansisan** [v3ss0n/goto#99]
On Atom 1.12.7 and Goto 1.8.2, and using Goto Project Symbol (or reindexing) I get the following stacktrace:

```
Error: "toString()" failed
    at Buffer.toString (buffer.js:503:11)
    at Object.fs.readFileSync (fs.js:552:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)
    at SymbolIndex.module.exports.SymbolIndex.processFile (/Users/dansisan/.atom/packages/goto/lib/symbol-index.coffee:154:15)
    at /Users/dansisan/.atom/packages/goto/lib/symbol-index.coffee:113:24
    at traverse (/Users/dansisan/.atom/packages/goto/node_modules/fs-plus/lib/fs-plus.js:419:13)
    at Object.traverseTreeSync (/Users/dansisan/.atom/packages/goto/node_modules/fs-plus/lib/fs-plus.js:424:14)
    at SymbolIndex.module.exports.SymbolIndex.rebuild (/Users/dansisan/.atom/packages/goto/lib/symbol-index.coffee:111:10)
    at atom-workspace.atom.commands.add.goto:rebuild-index (/Users/dansisan/.atom/packages/goto/lib/index.coffee:31:39)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1136:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:319:25)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
```

Goto File Symbol works fine.

**Comment by dansisan** [comment]
On further investigation, the problem is caused by a very large file in my project -- but it's an ignored file type (defined in .gitignore) and I would not have expected it to be processed.
